### ISSUE TITLE
Allowing negative curve amplitudes

### ISSUE THREAD

**Issue by dkeenan7** [christianp/aperiodic-monotile#4]
Thanks for this great tool. I would love to be able to see what the spectre looks like with the curves going the other way (i.e. going in where they used to go out and vice versa). It would also be great if we could choose an integer number of half-waves per side, say from 1 to 4) (currently fixed at 2). And fun if we could choose other waveforms besides sine, such as triangle and square, or trapezoid.

**Comment by christianp** [comment]
This would be nice, but I don't think I'm going to do it. Really you only need something to break reflection symmetry, it doesn't matter what.

**Comment by alreadydone** [comment]
> what the spectre looks like with the curves going the other way (i.e. going in where they used to go out and vice versa)

I think you just need to adjust the lower limit of the slider to -1 here: https://github.com/christianp/aperiodic-monotile/blob/49ea8d55f05d150168e66f662020ac7ad14a709d/interactive.html#L72

> choose an integer number of half-waves per side, say from 1 to 4) (currently fixed at 2)

https://github.com/christianp/aperiodic-monotile/blob/49ea8d55f05d150168e66f662020ac7ad14a709d/spectre-monotile-outline.scad#L42

Can be achieved by replacing 360 by 180~720 here, I think.

> And fun if we could choose other waveforms besides sine, such as triangle and square, or trapezoid.

Have you seen https://www.desmos.com/calculator/vh3z0qhlrq?lang=ja and all the cray shapes [here](https://threadreaderapp.com/thread/1663359915531051008.html) (also [here](https://youtu.be/OImGgciDZ_A?t=1886))?
